apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: appsody7
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: appsody7 
  stack: java-microprofile
  service:
    type: NodePort
    port: 9080
    annotations:
      prometheus.io/scrape: 'true'
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
